---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/main/schema/compose-spec.json
services:
  ghost:
    image: ghost:6-alpine
    restart: no
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: development
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      logging__level: debug
      mail__transport: SMTP
      mail__from: ghost@localhost
      mail__options__host: mailpit
      mail__options__port: 1025
    volumes:
      - ghost_data:/var/lib/ghost/content
      - ../theme:/var/lib/ghost/content/themes/vaida:ro
      - ../routes.yaml:/var/lib/ghost/content/settings/routes.yaml:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ghost_network

  db:
    image: mysql:8.0.44@sha256:f37951fc3753a6a22d6c7bf6978c5e5fefcf6f31814d98c582524f98eae52b21
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
      MYSQL_DATABASE: ghost
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -proot -h 127.0.0.1
      interval: 1s
      start_period: 30s
      start_interval: 10s
      retries: 120
    networks:
      - ghost_network

  mailpit:
    image: axllent/mailpit:latest
    restart: no
    ports:
      - "8025:8025"
    networks:
      - ghost_network

  adminer:
    image: adminer:latest
    restart: no
    ports:
      - "8090:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ghost_network

volumes:
  ghost_data:
  db_data:

networks:
  ghost_network:
